name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: egdsandaru

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker version

      - name: Configure Docker credentials
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build and push Docker images
        run: |
          CONFIG=$(cat config.json)
          for image in $(echo "${CONFIG}" | /usr/bin/jq -r '.images[] | @base64'); do
            IMAGE=$(echo "${image}" | base64 --decode | jq -r '.')
            IMAGE_NAME=$(echo "${IMAGE}" | /usr/bin/jq -r '.name')
            PATH=$(echo "${IMAGE}" | /usr/bin/jq -r '.path')
            VERSION=$(echo "${IMAGE}" | /usr/bin/jq -r '.version')

            # Check if image with version exists in registry
            if /usr/bin/docker manifest inspect $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION > /dev/null 2>&1; then
              echo "Image $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION already exists. Skipping build and push."
            else
              # Build and push Docker image
              /usr/bin/docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION $PATH
              /usr/bin/docker push $DOCKER_REGISTRY/$IMAGE_NAME:$VERSION
            fi
          done

#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
